### ISSUE TITLE
Program fails to load json file

### ISSUE THREAD

**Issue by tvand08** [natethebosch/timetracker#1]
## Issue 
- The file is capable of being corrupted and therefore rendered useless

## Reproduce
- Run timetrack 
- Force quit
- Run timetrack
- Verify that the program exits with exit status 1

**Comment by ntbosscher** [comment]
@tvand08 thanks for reporting this! If you have a minute can you verify that #2 fixes your issue?

Thanks,
Nate

**Comment by tvand08** [comment]
#2 fixes the current issue!

Thanks for the quick fix,
Trevor
